### ISSUE TITLE
Merge t1 and t3 faiss index building code.

### ISSUE THREAD

**Issue by maumueller** [harsha-simhadri/big-ann-benchmarks#10]

**Comment by mdouze** [comment]
Are you sure you want to do that? I specifically split the building code in two because there was too much T3-specific code and the T1 code is already hairy enough.

**Comment by maumueller** [comment]
Ok, let's keep them separate then. From the outside, it just looks like 

https://github.com/harsha-simhadri/big-ann-benchmarks/blob/gw/T3/benchmark/algorithms/faiss_t1.py#L80-L239

and 

https://github.com/harsha-simhadri/big-ann-benchmarks/blob/gw/T3/benchmark/algorithms/faiss_t3.py#L55-L205

should really be refactored into one.
