### ISSUE TITLE
Please share the results publically

### ISSUE THREAD

**Issue by KShivendu** [harsha-simhadri/big-ann-benchmarks#126]
Hello, are the results out? If yes, can you please share the results publicly? Ideally, something like https://ann-benchmarks.com/ graphs would be great. 

Thanks!

**Comment by Adam-D-Lewis** [comment]
Raw data and graphs would be even better!

**Comment by harsha-simhadri** [comment]
Added plots for NeurIPS'23. Will add plots for NeurIPS'21 as well.
