### ISSUE TITLE
Docker build problems

### ISSUE THREAD

**Issue by CaucherWang** [harsha-simhadri/big-ann-benchmarks#131]
I met problems when building docker images in neurips23 dir.
`apt-get update`: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/.deb /var/cache/apt/archives/partial/.deb /var/cache/apt/*.bin || true'
`pip3 install ...`: RuntimeError: can't start new thread

But when I change the ubuntu base image from jammy to 20.04, the problems are fixed.
I think it might be because of the docker version (mine is 20.10.7). I don't see a specified version in this repo.
So I recommend the organizers share the docker version user in the evaluation machines.

**Comment by maumueller** [comment]
Using Ubuntu Jammy [seems to be the problem here](https://stackoverflow.com/questions/71941032/why-i-cannot-run-apt-update-inside-a-fresh-ubuntu22-04). I used `24.0.2`, but the linked thread suggests that it will already work with at least `20.10.14`.

**Comment by sourcesync** [comment]
FYI...I used 23.0.3.

Client: Docker Engine - Community
 Version:           23.0.3
 API version:       1.42
 Go version:        go1.19.7
 Git commit:        3e7cbfd
 Built:             Tue Apr  4 22:05:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.3
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       59118bf
  Built:            Tue Apr  4 22:05:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by sourcesync** [comment]
FYI, I used 23.0.3.

-----

Client: Docker Engine - Community
 Version:           23.0.3
 API version:       1.42
 Go version:        go1.19.7
 Git commit:        3e7cbfd
 Built:             Tue Apr  4 22:05:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.3
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       59118bf
  Built:            Tue Apr  4 22:05:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by CaucherWang** [comment]
Thanks for your help and updates. With a higher version of Docker 24.0.2, the problems are fixed.
