### ISSUE TITLE
where is diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl?

### ISSUE THREAD

**Issue by heaoxiang** [harsha-simhadri/big-ann-benchmarks#147]
when building neurips23-ood-diskann...
 => ERROR [11/12] RUN pip install dist/diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl                                       1.4s 
------                                                                                                                            
 > [11/12] RUN pip install dist/diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl:                                                  
1.266 WARNING: Requirement 'dist/diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl' looks like a filename, but the file does not exist                                                                                                                                
1.299 Processing ./dist/diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl                                                           
1.307 ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/app/DiskANN/dist/diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl'
1.307 
------
Dockerfile:13
--------------------
  11 |     RUN pip3 install virtualenv build
  12 |     RUN python3 -m build
  13 | >>> RUN pip install dist/diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl
  14 |     WORKDIR /home/app
  15 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install dist/diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl" did not complete successfully: exit code: 1

it seems diskann doesnt have dist/ directory

**Comment by maumueller** [comment]
Thanks @heaoxiang. Could you check @harsha-simhadri?

**Comment by heaoxiang** [comment]
> Thanks @heaoxiang. Could you check @harsha-simhadri?

ok, should I wait for his reply or open an issue in diskann?

and when I  run python3  install.py --neurips23track ood       --algorithm diskann

it hints 
Traceback (most recent call last):
  File "/Users/heaoxiang/big-ann-benchmarks/install.py", line 6, in <module>
    import neurips23.common
  File "/Users/heaoxiang/big-ann-benchmarks/neurips23/common.py", line 7, in <module>
    from neurips23.streaming.run import StreamingRunner
  File "/Users/heaoxiang/big-ann-benchmarks/neurips23/streaming/run.py", line 39
    match entry['operation']:
          ^
SyntaxError: invalid syntax

Comment the code related to StreamingRunner to run the code
Is there something wrong with your code?

**Comment by maumueller** [comment]
> ok, should I wait for his reply or open an issue in diskann?

The problem you pointed to is probably related to a recent change in the framework and not related to diskann. 

> Is there something wrong with your code?

No, your Python version is just out-dated. We require to use Python >= 3.10.

**Comment by heaoxiang** [comment]
> The problem you pointed to is probably related to a recent change in the framework and not related to diskann.

ok fine.

**Comment by heaoxiang** [comment]
> No, your Python version is just out-dated. We require to use Python >= 3.10.

This error will be reported when using python3.8, and it will be gone when using the 3.10 version

**Comment by heaoxiang** [comment]
@harsha-simhadri help me , my friend

**Comment by maumueller** [comment]
@harsha-simhadri I looked at this and although you check out the 0.5.0rc3 branch, the wheel file is still called _0.5.0rc2_. 

This would work, but is probably not what you intended:

```diff
-RUN pip install dist/diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl
+RUN pip install dist/diskannpy-0.5.0rc2-cp310-cp310-linux_x86_64.whl
```

**Comment by heaoxiang** [comment]
> This would work, but is probably not what you intended:
right, thanks!
