### ISSUE TITLE
DataSet Format Question

### ISSUE THREAD

**Issue by Coien-rr** [harsha-simhadri/big-ann-benchmarks#154]
When I look at the meta file for the yfcc100M dataset I can only get the first two values as the number of nodes and the number of labels,
For the description of the latter data format I guess it is the sparse matrix format but I can't tell for sure
Please tell me where should I get more information from
Thx!!!!!!!!

**Comment by maumueller** [comment]
Hi @Coien-rr 

Are you using [`get_dataset_metadata()`](https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/benchmark/datasets.py#L635-L636)? It returns a [standard CSR matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html).

We use it in this baseline: https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/neurips23/filter/faiss/faiss.py

**Comment by Coien-rr** [comment]
got it, i will try it. Thank you !

**Comment by Coien-rr** [comment]
> Hi @Coien-rr
> 
> Are you using [`get_dataset_metadata()`](https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/benchmark/datasets.py#L635-L636)? It returns a [standard CSR matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html).
> 
> We use it in this baseline: https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/neurips23/filter/faiss/faiss.p

**Comment by Coien-rr** [comment]
> Hi @Coien-rr
> 
> Are you using [`get_dataset_metadata()`](https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/benchmark/datasets.py#L635-L636)? It returns a [standard CSR matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html).
> 
> We use it in this baseline: https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/neurips23/filter/faiss/faiss.py

I have obtained the sparse matrix representation of the label information, thank you very much, but I would like to ask how to obtain the categorical representation of the labels, as expressed on the first page of the contest
> we associate with each image a "bag" of tags: words extracted from the description, the camera model, the year the picture was taken and the country. The tags are from a vocabulary of 200386 possible tags. 

Or the semantic representation of the word before it was encoded

**Comment by maumueller** [comment]
Adding @mdouze because he worked on the preparation code. 

The process to obtain the metadata is detailed here: https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/dataset_preparation/prepare_yfcc100m.py It is not exactly reproducible at this point and requires some manual changes if you want to run it yourself.

For the challenge, you don't need to worry about the metadata. The individual tags are the integers that you find in the sparse matrix. I'm not sure if the integer -> tag mapping is available, but @mdouze certainly knows.

**Comment by mdouze** [comment]
Right, for the curious, the integer -> tag mapping is available here: 

https://dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/yfcc100M/words.txt

but as @maumueller mentions, it is not necessary to have this mapping to perform the task. 
The file format for sparse matrices is described here: 

https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/benchmark/dataset_io.py#L191

Or, in plain text: 

```
int64   nrow: number of rows of the matrix 
int64   ncol: number of columns of the matrix 
int64   nnz:  number of non-0 elements in the matrix
int64[nrow + 1] indptr:  pointers to the beginning of each row
int32[nnz]      indices: row indices of each entry
int32[nnz]      data:    corresponding non-zero matrix values 
```

It is a sparse CSR representation, so the non-0 entries of row i=0..nrow-1 are in columns 

   indices[indptr[i]] to indices[indptr[i+1]-1]

With matrix entries 

   data[indptr[i]] to data[indptr[i+1]-1]

In the case of filtered search, the data entries will not be used, so maybe we can make that optional.

**Comment by Coien-rr** [comment]
Thanks for your help,  @mdouze @maumueller 
my problem is solved and this dataset is so damn interesting!
