### ISSUE TITLE
Incorrect diskann dockerfiles

### ISSUE THREAD

**Issue by landrumb** [harsha-simhadri/big-ann-benchmarks#163]
When running `python install.py --neurips23track ood       --algorithm diskann` or `python install.py --neurips23track streaming --algorithm diskann`, an issue is encountered where the installation of diskann fails because the file name for the compiled diskann is specified as `dist/diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl` when the file created by the build is `dist/diskannpy-0.5.0rc2-cp310-cp310-linux_x86_64.whl`.

This seems to stem from [this commit](https://github.com/harsha-simhadri/big-ann-benchmarks/commit/4b096fc5da819bb480e3e38b88e1835c03b50db9) in which the diskann version is upgraded to rc3, but the rc3 branch does not seem to compile an output with the correct name, causing the issue. 

Fixed for me by changing the filename in the dockerfiles as described, but if the upgrade to rc3 matters it might therefore not be getting applied.

**Comment by 9p6p** [comment]
> [11/12] RUN pip install dist/diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl:                                                                                                                            
#0 1.143 WARNING: Requirement 'dist/diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl' looks like a filename, but the file does not exist                                                                     
#0 1.172 Processing ./dist/diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl
#0 1.179 ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/app/DiskANN/dist/diskannpy-0.5.0rc3-cp310-cp310-linux_x86_64.whl'
#0 1.179 
------

I can't find this file，where is it？

**Comment by nk2014yj** [comment]
meet the same problem

**Comment by nk2014yj** [comment]
Using blow cmd in dockerfile, find file diskannpy-0.5.0rc2-cp310-cp310-linux_x86_64.whl.
If pip install diskannpy-0.5.0rc2-cp310-cp310-linux_x86_64.whl is OK？ 

Step 11/13 : RUN ls -al dist && sleep 10
 ---> Running in e4d6640670e2
total 5048
drwxr-xr-x 2 root root    4096 Sep 11 09:27 .
drwxr-xr-x 1 root root    4096 Sep 11 09:25 ..
-rw-r--r-- 1 root root 4942172 Sep 11 09:27 diskannpy-0.5.0rc2-cp310-cp310-linux_x86_64.whl
-rw-r--r-- 1 root root  214162 Sep 11 09:25 diskannpy-0.5.0rc2.tar.gz

**Comment by 9p6p** [comment]
the diskannpy-0.5.0rc2-cp310-cp310-linux_x86_64.whl is OK, it looks fine.But why rc3 file disapear

**Comment by daxpryce** [comment]
Note: I can also publish a new tag, but once again, we'll need to update the Dockerfile to point to the correct tag (even if it is still going to be the fixed release tag for 0.5.0.rc3)

**Comment by daxpryce** [comment]
Version is properly published and tagged @ 0.5.0.rc3.post1

See comparison: https://github.com/microsoft/DiskANN/compare/0.5.0.rc3...0.5.0.rc3.post1

See github tag: https://github.com/microsoft/DiskANN/tree/0.5.0.rc3.post1
See github release: https://github.com/microsoft/DiskANN/releases/tag/0.5.0.rc3.post1
See pypi published release: https://pypi.org/project/diskannpy/0.5.0rc3.post1/

**Comment by harsha-simhadri** [comment]
Dax, Thanks for publishing the release. Sorry for overlooking the old tag. I will work on a PR to change the version in the baseline.
