### ISSUE TITLE
OODtrack：the text2image1B/gt100-heldout.30K.fbin file seems fault

### ISSUE THREAD

**Issue by 9p6p** [harsha-simhadri/big-ann-benchmarks#165]
for the result it over 10000000 and can't use it to calculate recall
what's the problem?
![image](https://github.com/harsha-simhadri/big-ann-benchmarks/assets/85789412/db73a0e8-4ba3-4088-9ed3-d31efa78e979)

**Comment by 9p6p** [comment]
above is the first ten results in the gt file

**Comment by 9p6p** [comment]
another problem is:
in the `python run.py --neurips23track ood       --algorithm diskann --dataset random-xs`, the distance is euclidean.
but in the `python run.py --neurips23track ood       --algorithm diskann --dataset text2image-10M`, the distance is ip,
which distance should i choose?

**Comment by 9p6p** [comment]
@harsha-simhadri @DmitryKey

**Comment by nk2014yj** [comment]
Every dataset has its constant distance type. 
In file benchmark/datasets.py, it contains all the datasets that this benchmark supports. The function "def distance(self)" return the distance type of a dataset.

**Comment by 9p6p** [comment]
> Every dataset has its constant distance type. In file benchmark/datasets.py, it contains all the datasets that this benchmark supports. The function "def distance(self)" return the distance type of a dataset.

I just want to konw, why in the same track, the sample "random-xs" distance is different from "text2image-10M"

**Comment by 9p6p** [comment]
> above is the first ten results in the gt file

maybe this is the "base_1B.fbin" gt file, for this, the organizer didn't provide the gt file of "text2image-10M"

**Comment by nk2014yj** [comment]
random-xs is a very small dataset. random-xs could be used to quickly test the configuration of your alg is ok. the distance type of random-xs is irrelevant.

**Comment by 9p6p** [comment]
> random-xs is a very small dataset. random-xs could be used to quickly test the configuration of your alg is ok. the distance type of random-xs is irrelevant.

ok, thx
