### ISSUE TITLE
the application scenario of Streaming 

### ISSUE THREAD

**Issue by nk2014yj** [harsha-simhadri/big-ann-benchmarks#168]
The  increment dataset is reordered according to clustering results.
Based on our experience，data distribution in service application is random. 
I want to know what kind of scenario is simulated. Thanks

**Comment by nk2014yj** [comment]
In a specific application, it is common to know the machine learning model which is used to extract features and the rough feature data distribution is known.

**Comment by nk2014yj** [comment]
According to neurips23/streaming/delete_runbook.yaml, the ratio  of insertion operations, deletion operations, and search commands is roughly  4  : 1 : 4.
will this ratio keep basically unchanged ？

**Comment by harsha-simhadri** [comment]
> The increment dataset is reordered according to clustering results. Based on our experience，data distribution in service application is random. I want to know what kind of scenario is simulated. Thanks

I agree that most real world cases would not be as "hard" as this. But the goal is to encourage algorithms that are robust to distribution change. Clustered-runbook represents one extreme example you might want to prove an algo on.

**Comment by harsha-simhadri** [comment]
> According to neurips23/streaming/delete_runbook.yaml, the ratio of insertion operations, deletion operations, and search commands is roughly 4 : 1 : 4. will this ratio keep basically unchanged ？

I will release the final runbook for this track by Oct 10.  The ratio will be in this ball park
