### ISSUE TITLE
[NeurIPS'23] When is the exact deadline?

### ISSUE THREAD

**Issue by maronuu** [harsha-simhadri/big-ann-benchmarks#196]
The official web site says that the deadline is October 30th, but there are some comments in issues or PRs from organizers that say October 31st.

When is the exact deadline? And could you please specify the timezone?

Thank you

**Comment by harsha-simhadri** [comment]
Please submit as soon as possible, no later than Oct 31.

**Comment by maronuu** [comment]
Thank you for the response, so you mean the deadline is Oct 31 (AoE), right?

**Comment by harsha-simhadri** [comment]
I would not recommend waiting that late. As you on open PRs, submissions have been failing to run and I tryign to work with authors to resolve issues. Changes at the last minute are difficult for us to test.

**Comment by maronuu** [comment]
OK, I understand that. Thank you for kind response.
I'm now closing the issue.
