### ISSUE TITLE
Request for T2 baseline search parameters

### ISSUE THREAD

**Issue by DelightRun** [harsha-simhadri/big-ann-benchmarks#25]
I tried to reproduce the T2 baseline using official indices and codes in PR https://github.com/harsha-simhadri/big-ann-benchmarks/pull/17, but cannot get reasonable results compared to the official baseline(i.e. 2000QPS, 0.957 Recall@10 for BIGANN-1B). So would you please release your code and configurations for T2 baseline evaluation?

Here is my operations and results for BIGANN-1B:
1. Buy a Standard_L8s virtual machine from Azure with Ubuntu 20.04
2. Install necessary softwares such as Docker, Anaconda, CMake, etc.
3. Checkout code of PR https://github.com/harsha-simhadri/big-ann-benchmarks/pull/17
4. Run `pip install -U -r requirements_py38.txt` to install python requirements
5. Run `python install.py` to build docker images
6. Run `python run.py --dataset bigann-1B --algorithm diskann-t2`
7. Run `python data_export.py --output result.csv` to export results

The final results are as follows:
```
algorithm,parameters,dataset,count,qps,distcomps,build,indexsize,queriessize,wspq,recall/ap
diskann-t2,DiskANN,bigann-1B,10,883.7374471075963,0.0,1000000.0,51774612.0,58585.96596698971,inf,0.0019
diskann-t2,DiskANN,bigann-1B,10,1307.73774493947,0.0,1000000.0,51774612.0,39590.97471977949,inf,0.00108
diskann-t2,DiskANN,bigann-1B,10,803.5946779065205,0.0,1000000.0,51774612.0,64428.764181067374,inf,0.00208
diskann-t2,DiskANN,bigann-1B,10,1118.5931944484782,0.0,1000000.0,51774612.0,46285.4702289937,inf,0.00133
diskann-t2,DiskANN,bigann-1B,10,1604.1311836371815,0.0,1000000.0,51774612.0,32275.796722938252,inf,0.00076
diskann-t2,DiskANN,bigann-1B,10,929.937028492744,0.0,1000000.0,51774612.0,55675.39565976534,inf,0.0017500000000000003
diskann-t2,DiskANN,bigann-1B,10,966.1165292100424,0.0,1000000.0,51774612.0,53590.44218230504,inf,0.0017399999999999998
diskann-t2,DiskANN,bigann-1B,10,990.0256363593018,0.0,1000000.0,51774612.0,52296.23365147877,inf,0.00166
diskann-t2,DiskANN,bigann-1B,10,1051.6221286578705,0.0,1000000.0,51774612.0,49233.09484375076,inf,0.00149
diskann-t2,DiskANN,bigann-1B,10,682.3607260592325,0.0,1000000.0,51774612.0,75875.72089473638,inf,0.00258
```

**Comment by harsha-simhadri** [comment]
Could you please try again with master branch. The results I see with the commands you are listed are on https://github.com/harsha-simhadri/big-ann-benchmarks/pull/31

**Comment by harsha-simhadri** [comment]
@DelightRun Were you able to run these params?

**Comment by harsha-simhadri** [comment]
Please re-open if there is an issue
