### ISSUE TITLE
The algorithm does not have open source code

### ISSUE THREAD

**Issue by DorritTang** [harsha-simhadri/big-ann-benchmarks#251]
https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/neurips23/streaming/hwtl_sdu_anns_stream/Dockerfile

In this algo, it only provides an installation package. Is it compliant with the requirements?

**Comment by maumueller** [comment]
This seems to be the diskann baseline with different parameters. I agree that it's odd to not just use the diskann Dockerfile in this case. What do you think @harsha-simhadri?

**Comment by harsha-simhadri** [comment]
Martin, agree. They seem to be reusing diskann python wrapper release 0.5.0rc3. The source for that version can be found here: https://github.com/microsoft/DiskANN/releases/tag/0.5.0.rc3.post1

**Comment by amallia** [comment]
> They seem to be reusing diskann python wrapper release 0.5.0rc3

I have decompiled the code, and I can say that the DiskANN code has been modified.

**Comment by harsha-simhadri** [comment]
@WPJiang Can you share the source for this entry and whether it has modified DiskANN. Thank you.

**Comment by WPJiang** [comment]
> @WPJiang Can you share the source for this entry and whether it has modified DiskANN. Thank you.

The index construction part of DiskANN has been modified, the most obvious evidence is that ,as @amallia said, the original  one can not terminate in 1h.  The source code is considered to be available at some time in the future. Due to certain policies of our organization, we are currently unable to provide the source code. Sorry about that.

**Comment by harsha-simhadri** [comment]
> > @WPJiang Can you share the source for this entry and whether it has modified DiskANN. Thank you.
> 
> The index construction part of DiskANN has been modified, the most obvious evidence is that ,as @amallia said, the original one can not terminate in 1h. The source code is considered to be available at some time in the future. Due to certain policies of our organization, we are currently unable to provide the source code. Sorry about that.

@WPJiang Thanks for the clarification. I will make a note of this on the leaderboard.
