### ISSUE TITLE
[NeurIPS'23] Question on a format of 1-page summary

### ISSUE THREAD

**Issue by maronuu** [harsha-simhadri/big-ann-benchmarks#253]
### Question
What is a format of 1-page summary of a solution described in the email from CMT?

@harsha-simhadri

**Comment by harsha-simhadri** [comment]
Please use whatever format you think appropriate. Share an overview of ideas.. what are you building on, what are the new ideas or optimizations that worked well for you. We will discuss with you to make sure we understand before we present at the NeurIPS session
