### ISSUE TITLE
Bug? when running evaluate

### ISSUE THREAD

**Issue by TokyoWolFrog** [harsha-simhadri/big-ann-benchmarks#27]
Hi ! Thanks for providing the scripts for evaluating  results.

I found that when running `python data_export.py --output res.csv`,
this line of code: 
[`power_capture.detect_power_benchmarks(metrics, res)`](https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/benchmark/plotting/utils.py#L79)
will run out the yield generator **res**,
so the next line:
[`for i, (properties, run) in enumerate(res):`](https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/benchmark/plotting/utils.py#L82)
don't  output anything to be write into res.csv. 

I'm still studying the code, and not sure if this is a bug...

**Comment by maumueller** [comment]
You are completely right! @gosha1128, didn't we discuss this at some point (and even fix it)?

**Comment by gosha1128** [comment]
Yes. I'll look into it ASAP...

**Comment by gosha1128** [comment]
Hi @TokyoWolFrog, I believe I have created a fix for your issue.  If possible, can you validate this [pull request](https://github.com/harsha-simhadri/big-ann-benchmarks/pull/28) and then I will merge into main.

**Comment by TokyoWolFrog** [comment]
@maumueller @gosha1128 
 Thank you very much for the prompt response！
I have run the [pull request](https://github.com/harsha-simhadri/big-ann-benchmarks/pull/28) and it works for me!
Thanks again!
