### ISSUE TITLE
If an algo makes heavy use of the filesystem cache, is it T1 or T2?

### ISSUE THREAD

**Issue by alexklibisz** [harsha-simhadri/big-ann-benchmarks#39]
If an algorithm primarily stores its structures on disk, but makes heavy use of the filesystem cache to speedup access to those structures, does it belong in T1 or T2?

Some concrete examples:
- Elastiknn uses Lucene, which makes heavy use of the filesystem cache, memmapping, etc.
- Annoy is able to read from memmapped files ("Annoy also decouples creating indexes from loading them, so you can pass around indexes as files and map them into memory quickly.")

I personally think they should fall under T2, but I could see arguments for both. Anyway, it would be good to clarify this somewhere in the readme or website if possible.

**Comment by harsha-simhadri** [comment]
I would say T2 as well. The idea in T1 is to limit the index to what can be held in DRAM with limited footprint. Using Disk would allow the algo to store higher precision vectors and larger indices, which is the goal in T2.

**Comment by alexklibisz** [comment]
That makes sense. I'll go ahead and close this and proceed on T2.
