### ISSUE TITLE
Storage type

### ISSUE THREAD

**Issue by masajiro** [harsha-simhadri/big-ann-benchmarks#45]
Thank you for providing such a great competition.
I would like to confirm the SSD storages for T1 and T2 hardware. Which storage type is used for them, standard, premium or ultra disk? Compared to physical SSD, the standard and premium are very slow to build indexes. I haven’t tried the ultra disk yet.

**Comment by harsha-simhadri** [comment]
For building indices in T1, T2, we will use a premium SSD. This is not necessarily local to the machine and it's I/O rate is throttled. Please take this into consideration for building indices.
For T2 search, the machine has a local SSD as provided by the Lsv2-series.

**Comment by masajiro** [comment]
Thanks!
