### ISSUE TITLE
Evaluation of Track 2: on-disk index size constraint

### ISSUE THREAD

**Issue by miguelpinho** [harsha-simhadri/big-ann-benchmarks#46]
The 1TB constraint for the local SSD index is quite lower than the 1.92 TB available on the NVMe disk of the Azure Standard_L8s_v2 VMs. Could this constraint be increased?

**Comment by harsha-simhadri** [comment]
Not for the NeurIPS'21 competition since we committed to 1TB. We can relax this later as the site evolves
