### ISSUE TITLE
Evaluation of Track 2: Building new index by starting from existing baseline indexes

### ISSUE THREAD

**Issue by miguelpinho** [harsha-simhadri/big-ann-benchmarks#47]
Could the building of the index (which has a 4 days constraint) start by downloading one of the available baseline indexes, and then apply changes to it (possibly taking a couple of days)?

**Comment by harsha-simhadri** [comment]
For T1, the published indices take much less than the 4 day limit. So downloading and editing them for 2 days is fair. For T2, the published indices take 3+ days to build. So downloading and editing them will violate 4 day limit. One possibility is to build T2 indices with lower R and L parameters so it completes in 2 days and then do 2 days of editing.

**Comment by miguelpinho** [comment]
Thank you, using a lower R and L seems a good way to go. Actually, it will also speed up the editing we have in mind. Do you have any idea what ranges of R/L will fit in the 2 days?

**Comment by harsha-simhadri** [comment]
You would have to run and see. I would guess R of 64 and L 64 might run in 2 days, but that's a guess.
