### ISSUE TITLE
Radius value used for evaluation in range search

### ISSUE THREAD

**Issue by PwzXxm** [harsha-simhadri/big-ann-benchmarks#51]
Hi there,

There is a default value for radius here https://github.com/harsha-simhadri/big-ann-benchmarks/blob/e29a4fa45526c36fe04c65704dca558a519f897e/dataset_preparation/make_groundtruth.py#L241.

I am wondering will this default value **96237** be used for the final evaluation in the benchmark?

**Comment by harsha-simhadri** [comment]
Yes, and thanks for the pointer too.
