### ISSUE TITLE
Separate definitions file for T3 algorithms

### ISSUE THREAD

**Issue by gosha1128** [harsha-simhadri/big-ann-benchmarks#8]
@maumueller T3 algorithms will be tied to certain hardware.  Instead of putting T3 algo definitions in the default algos.yaml, would it be better to put them into a separate one?

**Comment by maumueller** [comment]
Yes, I think that's an excellent idea and we should also use it to separate T1 and T2 implementations :-)

**Comment by gosha1128** [comment]
Thanks, closing issue.
