### ISSUE TITLE
Incorrect result of BBAnn on text2image public query set

### ISSUE THREAD

**Issue by PwzXxm** [harsha-simhadri/big-ann-benchmarks#85]
It might be a mistake that in the [t1_t2/README.md](https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/t1_t2/README.md), the result of BBAnn (track 2) on text2image is incorrect.

As we discussed in PR #70, the best entry on the public query set is when QPS is 1540.622672933968, the recall is 0.495423.

We would be grateful if you would update the entry in the results section.

**Comment by harsha-simhadri** [comment]
fixed
